-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.82.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20/09/2024 12:12:00
-- Server version: 5.5.5-10.6.10-MariaDB-1:10.6.10+maria~ubu2004
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE santoro_user_image;

--
-- Definition for table role
--
DROP TABLE IF EXISTS role;
CREATE TABLE role (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table roles
--
DROP TABLE IF EXISTS roles;
CREATE TABLE roles (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table user
--
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) DEFAULT 'NULL',
  `password` VARCHAR(255) DEFAULT 'NULL',
  username VARCHAR(255) DEFAULT 'NULL',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 21
AVG_ROW_LENGTH = 819
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table users
--
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX username (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 19
AVG_ROW_LENGTH = 2340
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table image
--
DROP TABLE IF EXISTS image;
CREATE TABLE image (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  user_id BIGINT(20) DEFAULT NULL,
  content_type VARCHAR(255) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  `data` LONGBLOB DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FKcvpnctgluno47ac6avana5sqf FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FKlxnnh0ir05khn8iu9tgwh1yyk FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 17
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table images
--
DROP TABLE IF EXISTS images;
CREATE TABLE images (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(50) DEFAULT 'NULL',
  `data` LONGBLOB DEFAULT NULL,
  user_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX user_id (user_id),
  CONSTRAINT images_ibfk_1 FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table user_roles
--
DROP TABLE IF EXISTS user_roles;
CREATE TABLE user_roles (
  role_id BIGINT(20) NOT NULL,
  user_id BIGINT(20) NOT NULL,
  PRIMARY KEY (role_id, user_id),
  CONSTRAINT FK55itppkw3i07do3h7qoclqd4k FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FKhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FKrhfovtciq1l558cw6udg0h0d3 FOREIGN KEY (role_id)
    REFERENCES role(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table role
--
-- Table santoro_user_image.role does not contain any data (it is empty)

-- 
-- Dumping data for table roles
--
INSERT INTO roles VALUES 
  (3, 'Admin'),
  (4, 'SuperUser'),
  (5, 'User');

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES 
  (1, 'provar1@mail.com', '1233458', 'PROVAe2'),
  (2, 'updat3e56@mail.com', '123345534678', 'Update555'),
  (3, 'updat53e56@mail.com', '1233455534678', 'Update5565'),
  (4, 'prova1@mail.com', '1233458', 'PROVA1'),
  (5, 'prova1@mail.com', '1233458', 'PROVA2'),
  (6, 'provaUFFi@mail.com', '12e33458', 'ProvaUFFi'),
  (7, 'provaUFFic@mail.com', '12e33458', 'ProvaUFFiciale'),
  (8, 'provaUFFic2@mail.com', '12e334258', 'ProvaUFFiciale2'),
  (9, 'provaUF2Fic2@mail.com', '12e334258', 'ProvaUFFiciale22'),
  (10, 'provaUF23Fic2@mail.com', '12e334258', 'ProvaUFFiciale23'),
  (11, 'provauff@mail.com', '12334F5678', 'provauff'),
  (12, 'prova18@mail.com', '1233458', 'PROVA18'),
  (13, 'prova19@mail.com', '1233458', 'PROVA19'),
  (14, 'prova19@mail.com', '1233458', 'PROVA19'),
  (15, 'prova21@mail.com', '1233458', 'PROVA20'),
  (16, 'prova22@mail.com', '12334458', 'PROVA21'),
  (17, 'prova22@mail.com', '12334458', 'PROVA21'),
  (18, 'prova23@mail.com', '12334458', 'PROVA23'),
  (19, 'prova23@mail.com', '123344e58', 'PROVA23'),
  (20, 'prova2w@mail.com', '123344e58', 'PROVA2w');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES 
  (12, 'PROVA16', 'prova16@mail.com', '1233458'),
  (13, 'PROVA25', '123344e58', 'prova27@mail.com'),
  (14, 'PROVAUFFICIALE1', '123344e58', 'provauff1@mail.com'),
  (15, 'PROVAUFFICIALE2', '123344e58', 'provauff2@mail.com'),
  (16, 'PROVAUFFICIALE3', '123344e58', 'provauff3@mail.com'),
  (17, 'UpdateImage', '123345678', 'updat3e@mail.com'),
  (18, 'Prova1', '123345678', 'prova1@mail.com');

-- 
-- Dumping data for table image
--
-- Table santoro_user_image.image does not contain any data (it is empty)

-- 
-- Dumping data for table images
--
-- Table santoro_user_image.images does not contain any data (it is empty)

-- 
-- Dumping data for table user_roles
--
-- Table santoro_user_image.user_roles does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;